<a href="https://colab.research.google.com/github/Alissa-Ouspen/data110_alissa/blob/main/useful_code/num_index_pandas_df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from matplotlib import pyplot as plt  # data visualization
import numpy as np                    # numerical computations
import pandas as pd                   # dataframes
#plt.style.use("ggplot")
plt.style.use("seaborn-v0_8")         # Sets the style for the plots

In [3]:
df = pd.read_csv("https://raw.github.com/Alissa-Ouspen/data110_alissa/main/week3/crime_data_22_23.csv")

In [4]:
df

,Offense,"Offenses per 100,000 People (2023)","Change in Offenses per 100,000 People (2022–2023)","Offenses per 100,000 People (2022)"
0,Aggravated Assault,264.1,-3.3,267.4
1,Burglary,250.7,-8.1,258.8
2,Larceny,1347.2,-4.9,1352.1
3,Motor Vehicle Theft,318.7,12.0,306.7
4,Murder,5.7,-12.0,17.7
5,Rape (revised definition),38.0,-9.8,47.8
6,Robbery,66.5,-0.8,67.3

### Demonstrating Numerical Indexing with `.iloc`

Let's see how to access data in your `df` DataFrame using numerical (positional) indexing with `.iloc`.

In [5]:
# Display the first row using .iloc
print("First row (position 0) using .iloc:")
display(df.iloc[0])  # only row 0

# first three rows [incl, excl]
# df.iloc[0:3]  # row 0, 1, 2

# Display the 'Offense' column (position 0) using .iloc
print("\nFirst column (position 0) using .iloc:")
display(df.iloc[:, 0])  # every row of col 0

# first two columns
# df.iloc[:, 0:2]

# Display the value at row 2, column 1 (position 2, 1) using .iloc
print("\nValue at row position 2, column position 1 (Aggravated Assault offense rate):")
display(df.iloc[2, 1])

First row (position 0) using .iloc:

Offense                                              Aggravated Assault
Offenses per 100,000 People (2023)                                264.1
Change in Offenses per 100,000 People (2022–2023)                  -3.3
Offenses per 100,000 People (2022)                                267.4
Name: 0, dtype: object

First column (position 0) using .iloc:

0           Aggravated Assault
1                     Burglary
2                      Larceny
3          Motor Vehicle Theft
4                       Murder
5    Rape (revised definition)
6                      Robbery
Name: Offense, dtype: object

Value at row position 2, column position 1 (Aggravated Assault offense rate):

np.float64(1347.2)